image: Visual Studio 2017
configuration:
 - ReleaseD3D12
 - ReleaseVK

build:
  project: Falcor.sln

before_package:
 - 7z a lib.zip Bin\x64\Release\ *.lib
 - 7z a exe.zip Bin\x64\Release\ *.exe
 
artifacts:
 - name: "Falcor.lib (x64)"
   path: Bin\Int\x64\Release*\Lib\Falcor.lib
 - name: "FalcorSharedObjects.lib (x64)"
   path: Bin\x64\Release\FalcorSharedObjects.lib
 - name: "All release .lib files (x64)"
   path: lib.zip
 - name: "All release .exe files (x64)"
   path: exe.zip
